; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = time
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-DNFC_INTERFACE_HSU
	-DPKE_ROLLOUT_BACKGROUND_MODE=0
	-DPKE_ROLLOUT_FAST_TRANSACTION=1
	-DPKE_ROLLOUT_BONDING_ENFORCE=0
	-DPKE_ROLLOUT_RSSI_MONITOR_ONLY=1
	-DPKE_ROLLOUT_RSSI_THRESHOLD_DBM=-70
	-DPKE_ROLLOUT_ADV_FAST_MIN_MS=30
	-DPKE_ROLLOUT_ADV_FAST_MAX_MS=60
	-DPKE_ROLLOUT_ADV_SLOW_MIN_MS=250
	-DPKE_ROLLOUT_ADV_SLOW_MAX_MS=500
	-DPKE_ROLLOUT_ADV_FAST_WINDOW_MS=15000
	-I test

lib_deps = 
	h2zero/NimBLE-Arduino@^2.3.6
	PN532
	# https://github.com/Seeed-Studio/PN532.git
