#pragma once
#include <stdint.h>

namespace FSM {

// All possible states
enum State {
  INIT,
  IDLE,
  PROVISIONING_WAIT_TAP,
  PROVISIONING_SELECT_AID,
  PROVISIONING_EXCHANGE_KEYS,
  PROVISIONING_STORE_CREDS,
  AUTH_WAIT_CONNECT,
  AUTH_HANDSHAKE,
  AUTH_VERIFY_KEYS,
  AUTH_SESSION_READY,
  UNLOCKING_CHECK_PROXIMITY,
  UNLOCKING_VERIFY_AUTH,
  UNLOCKING_EXECUTE,
  UNLOCKING_COMPLETE,
  ADMIN_MODE,
  ERROR_HANDLER
};

// Events that trigger state transitions
enum Event {
  SYSTEM_READY,
  TIMEOUT,
  ERROR_OCCURRED,
  RESET_REQUESTED,
  PROVISION_START,
  NFC_CARD_DETECTED,
  NFC_CARD_REMOVED,
  SELECT_AID_SUCCESS,
  SELECT_AID_FAILED,
  KEYS_EXCHANGED,
  KEYS_INVALID,
  CREDENTIALS_STORED,
  BLE_CLIENT_CONNECTED,
  BLE_CLIENT_DISCONNECTED,
  CLIENT_HELLO_RECEIVED,
  SERVER_HELLO_SENT,
  CLIENT_CONFIRM_RECEIVED,
  AUTH_VERIFIED,
  AUTH_FAILED,
  UNLOCK_REQUESTED,
  PROXIMITY_OK,
  PROXIMITY_TOO_FAR,
  AUTH_SESSION_VALID,
  AUTH_SESSION_EXPIRED,
  UNLOCK_EXECUTED,
  ADMIN_COMMAND,
  FORCE_PROVISION_ON,
  FORCE_PROVISION_OFF,
  CLEAR_KEYS,
  DIAGNOSTICS_REQUEST
};

// Error codes
enum ErrorCode {
  NONE = 0,
  NFC_INIT_FAILED,
  NFC_SAM_CONFIG_FAILED,
  NFC_TIMEOUT,
  NFC_APDU_FAILED,
  BLE_INIT_FAILED,
  BLE_DISCONNECT_UNEXPECTED,
  BLE_INVALID_DATA,
  CRYPTO_SIGNATURE_INVALID,
  CRYPTO_ECDH_FAILED,
  CRYPTO_HMAC_MISMATCH,
  STORAGE_WRITE_FAILED,
  STORAGE_READ_FAILED,
  INVALID_STATE_TRANSITION,
  NOT_PROVISIONED,
  SESSION_NOT_READY
};

// State info for debugging
struct StateInfo {
  State current;
  State previous;
  Event lastEvent;
  ErrorCode lastError;
  uint32_t enter_time;
};

const char* stateToString(State state);
const char* eventToString(Event event);
const char* errorToString(ErrorCode error);

} // namespace FSM

